### ISSUE TITLE
Homebridge crash ....

### ISSUE THREAD

**Issue by zokl** [zokl/openwrt-homebridge-sac#3]
Some error.

```
 Feb 14 13:13:16 2021 daemon.info homebridge[15585]: [Sun Feb 14 2021 13:13:16 GMT+0000 (UTC)] [Cmd4] Error: kill EPERM
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]:     at ChildProcess.kill (internal/child_process.js:492:26)
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]:     at kill (child_process.js:334:13)
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]:     at Timeout.delayedKill (child_process.js:343:7)
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]:     at listOnTimeout (internal/timers.js:549:17)
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]:     at processTimers (internal/timers.js:492:7) {
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]:   errno: 'EPERM',
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]:   code: 'EPERM',
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]:   syscall: 'kill',
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]:   cmd: "/usr/bin/sudo /bin/sh /usr/share/sac/sac-homebridge-wrapper.sh Get 'Somfy_Awning' 'CurrentPosition'"
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]: }
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]: [Sun Feb 14 2021 13:13:16 GMT+0000 (UTC)] [Cmd4]
Sun Feb 14 13:13:16 2021 daemon.info homebridge[15585]: [Sun Feb 14 2021 13:13:16 GMT+0000 (UTC)] [Cmd4]
Sun Feb 14 13:13:19 2021 authpriv.notice sudo: homebridge : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/sh /usr/share/sac/sac-homebridge-wrapper.sh Get Somfy_Awning CurrentPosition
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]: [Sun Feb 14 2021 13:13:21 GMT+0000 (UTC)] [Cmd4] getGeneric CurrentPosition function for:Somfy_Awning cmd:/usr/bin/sudo /bin/sh /usr/share/sac/sac-homebridge-wrapper.sh Get 'Somfy_Awning' 'CurrentPosition' failed.
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]: [Sun Feb 14 2021 13:13:21 GMT+0000 (UTC)] [Cmd4] Error: kill EPERM
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]:     at ChildProcess.kill (internal/child_process.js:492:26)
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]:     at kill (child_process.js:334:13)
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]:     at Timeout.delayedKill (child_process.js:343:7)
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]:     at listOnTimeout (internal/timers.js:549:17)
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]:     at processTimers (internal/timers.js:492:7) {
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]:   errno: 'EPERM',
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]:   code: 'EPERM',
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]:   syscall: 'kill',
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]:   cmd: "/usr/bin/sudo /bin/sh /usr/share/sac/sac-homebridge-wrapper.sh Get 'Somfy_Awning' 'CurrentPosition'"
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]: }
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]: [Sun Feb 14 2021 13:13:21 GMT+0000 (UTC)] [Cmd4]
Sun Feb 14 13:13:21 2021 daemon.info homebridge[15585]: [Sun Feb 14 2021 13:13:21 GMT+0000 (UTC)] [Cmd4]
Sun Feb 14 13:13:24 2021 daemon.info homebridge[15585]: [Sun Feb 14 2021 13:13:24 GMT+0000 (UTC)] Got SIGTERM, shutting down Homebridge...
Sun Feb 14 13:13:24 2021 authpriv.notice sudo: homebridge : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/sh /usr/share/sac/sac-homebridge-wrapper.sh Get Somfy_Awning CurrentPosition
Sun Feb 14 13:13:26 2021 daemon.info homebridge[15585]: [Sun Feb 14 2021 13:13:26 GMT+0000 (UTC)] [Cmd4] getGeneric CurrentPosition function for:Somfy_Awning cmd:/usr/bin/sudo /bin/sh /usr/share/sac/sac-homebridge-wrapper.sh Get 'Somfy_Awning' 'CurrentPosition' failed
```

**Comment by zokl** [comment]
The problem is hanged sac in reading several values. Workaround - stop sac, wait for closing all processes and then start it again and restart homebridge.
